# Generated by Django 3.1.5 on 2021-02-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0003_auto_20210207_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='name',
            new_name='discount',
        ),
    ]
