# Generated by Django 3.1.5 on 2021-03-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0013_auto_20210312_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addresss',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
