# Generated by Django 3.1.5 on 2021-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0014_auto_20210312_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addresss',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
