# Generated by Django 3.1.5 on 2021-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0015_auto_20210312_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addresss',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
