# Generated by Django 3.1.5 on 2021-03-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0020_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='Email',
        ),
    ]
