# Generated by Django 3.1.5 on 2021-03-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0022_orderplaced_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='transactionid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
