# Generated by Django 3.1.5 on 2021-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0023_auto_20210313_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='orderId',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='orderIds',
            field=models.CharField(default='', max_length=30),
        ),
    ]
