# Generated by Django 3.1.5 on 2021-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0027_auto_20210314_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='orderIds',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='transactionid',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='pincode',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
