# Generated by Django 3.1.5 on 2021-03-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0028_auto_20210314_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koshfurniture.customer'),
        ),
    ]
