# Generated by Django 3.1.5 on 2021-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0029_auto_20210314_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.TextField(max_length=200, null=True)),
                ('email', models.TextField(max_length=200, null=True)),
                ('password', models.TextField(max_length=200, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
