# Generated by Django 3.1.5 on 2021-03-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koshfurniture', '0030_cus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cus',
            name='date_joined',
        ),
    ]
